default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_project_66_development

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  database: rails_project_66_production
